"""
The buyer agent.

Flow for one recommendation:
  1. INVESTIGATE - the LLM calls read-only tools (inventory, forecast, open
     POs, supplier terms, budget, storage) as many times as it needs.
  2. DECIDE - the LLM calls submit_decision(decision, quantity, reasoning,
     key_factors). It never executes anything itself.
  3. VALIDATE (pre-execution) - deterministic Python re-derives the same
     numbers from the DB and checks budget / storage / MOQ / coverage.
     If it disagrees with the LLM, the LLM is told exactly why and gets a
     chance to revise (up to MAX_AGENT_REVISIONS times).
  4. EXECUTE - only after validation passes does the system actually create
     the purchase order. The LLM proposes; deterministic code disposes.
  5. VALIDATE (post-execution) - read the PO back from the DB and confirm
     it matches what was intended.
  6. ESCALATE - if validation keeps failing, or the decision deviates a lot
     from the original recommendation, the run is flagged for human review
     instead of auto-executing.
"""
import json
from anthropic import Anthropic

from app.config import AGENT_MODE, ANTHROPIC_API_KEY, ANTHROPIC_MODEL, MAX_AGENT_REVISIONS, MAX_TOOL_TURNS
from app.tools import TOOL_SCHEMAS, execute_tool
from app.db import db
from app.validator import validate_business_decision, validate_execution

SYSTEM_PROMPT = """You are an AI purchasing (buying) agent for a quick-commerce retailer.

You are reviewing a purchase recommendation generated by an upstream system. That
recommendation is a STARTING POINT ONLY and may be wrong - it might ignore existing
open purchase orders, budget limits, storage capacity, or the supplier's minimum
order quantity. Do not assume it is correct.

For each recommendation you must:
1. Investigate using the read-only tools: check current inventory, demand forecast,
   any open purchase orders already covering this product, the supplier's terms
   (lead time, minimum order quantity, unit price), the available budget, and the
   available storage capacity. Look things up rather than assuming.
2. Decide whether the recommendation should be:
   - accept: execute it exactly as given
   - modify: execute it but at a different quantity you specify
   - reject: no purchase should be made right now
   - investigate: you cannot make a confident decision with the available
     information, or there's a genuine conflict (e.g. real need is far below the
     supplier's minimum order quantity) that a human buyer should weigh in on
3. Call submit_decision exactly once with your decision, quantity (or null),
   reasoning that cites the actual numbers you looked up, and a short list of the
   key factors that drove the decision.

You do not create the purchase order yourself - that happens after your decision
is checked. If you are told your decision failed validation, re-read the reasons
carefully and submit a corrected decision.
"""


def _tool_result_block(tool_use_id: str, content: dict) -> dict:
    return {
        "type": "tool_result",
        "tool_use_id": tool_use_id,
        "content": json.dumps(content),
    }


def _append_user(messages: list, blocks: list) -> None:
    """Append user-role content blocks, merging into the previous turn if it
    was also a user turn. The API is documented to auto-merge consecutive
    same-role turns, but real-world reports of a hard 400 on this are common
    enough that we merge explicitly rather than rely on it."""
    if messages and messages[-1]["role"] == "user":
        messages[-1]["content"].extend(blocks)
    else:
        messages.append({"role": "user", "content": blocks})


def _investigate_and_decide(client: Anthropic, messages: list, trace: list) -> dict:
    """Runs the tool-use loop until submit_decision is called. Returns the decision dict."""
    for _ in range(MAX_TOOL_TURNS):
        response = client.messages.create(
            model=ANTHROPIC_MODEL,
            max_tokens=1500,
            system=SYSTEM_PROMPT,
            tools=TOOL_SCHEMAS,
            messages=messages,
        )
        messages.append({"role": "assistant", "content": response.content})

        if response.stop_reason != "tool_use":
            # Model stopped without submitting a decision - nudge it.
            _append_user(messages, [{"type": "text", "text": "Please call submit_decision with your final decision."}])
            continue

        tool_results = []
        decision = None
        for block in response.content:
            if block.type != "tool_use":
                continue
            if block.name == "submit_decision":
                decision = dict(block.input)
                trace.append({"type": "decision", "input": block.input})
                # Anthropic requires a tool_result for every tool_use, even the final one.
                tool_results.append(_tool_result_block(block.id, {"status": "received"}))
            else:
                result = execute_tool(block.name, block.input)
                trace.append({"type": "tool_call", "name": block.name, "input": block.input, "result": result})
                tool_results.append(_tool_result_block(block.id, result))

        _append_user(messages, tool_results)

        if decision is not None:
            return decision

    raise RuntimeError("Agent did not submit a decision within the tool-turn budget.")


def _complete_run(recommendation: dict, trace: list, decision_history: list,
                  final_decision: dict, validation: dict, escalated: bool = False) -> dict:
    """Execute a decision only after its independent validation has passed."""
    action_result = None
    if not escalated and final_decision["decision"] in ("accept", "modify"):
        po = db.create_po(
            recommendation["product_id"],
            recommendation["node_id"],
            recommendation["supplier_id"],
            final_decision["quantity"],
            recommendation.get("category", "default"),
        )
        exec_validation = validate_execution(
            po["po_id"], final_decision["quantity"], recommendation["supplier_id"]
        )
        action_result = {"purchase_order": po, "execution_validation": exec_validation}
        if not exec_validation["passed"]:
            escalated = True

    return {
        "recommendation": recommendation,
        "trace": trace,
        "decision_history": decision_history,
        "final_decision": final_decision,
        "validation": validation,
        "action_result": action_result,
        "escalated": escalated,
    }


def _run_demo_agent(recommendation: dict) -> dict:
    """Free, deterministic local mode for demonstrating the full agent flow.

    It deliberately calls the same read tools as the LLM mode, then applies
    transparent purchasing rules. This lets a reviewer run the complete demo
    without an external account while keeping Anthropic mode available.
    """
    product_id = recommendation["product_id"]
    node_id = recommendation["node_id"]
    supplier_id = recommendation["supplier_id"]
    category = recommendation.get("category", "default")
    calls = [
        ("get_inventory", {"product_id": product_id, "node_id": node_id}),
        ("get_demand_forecast", {"product_id": product_id, "node_id": node_id}),
        ("get_open_purchase_orders", {"product_id": product_id, "node_id": node_id}),
        ("get_supplier_terms", {"supplier_id": supplier_id}),
        ("get_budget_status", {"node_id": node_id, "category": category}),
        ("get_storage_capacity", {"node_id": node_id}),
    ]
    trace = []
    results = {}
    for name, tool_input in calls:
        result = execute_tool(name, tool_input)
        results[name] = result
        trace.append({"type": "tool_call", "name": name, "input": tool_input, "result": result})

    inventory = results["get_inventory"]["on_hand_qty"]
    forecast = results["get_demand_forecast"]["forecast_qty"]
    incoming = results["get_open_purchase_orders"]["total_open_qty"]
    supplier = results["get_supplier_terms"]
    budget = results["get_budget_status"]["available_amount"]
    capacity = results["get_storage_capacity"]["available_units"]
    existing_supply = inventory + incoming
    need = max(0, forecast - existing_supply)
    budget_limit = int(budget // supplier["unit_price"])
    storage_limit = max(0, capacity - existing_supply)
    safe_limit = min(budget_limit, storage_limit)
    recommended = recommendation["recommended_qty"]

    factors = [
        f"Current supply is {inventory} on hand + {incoming} already ordered = {existing_supply} units.",
        f"Forecast demand is {forecast} units; the uncovered need is {need} units.",
        f"Supplier MOQ is {supplier['min_order_qty']} and lead time is {supplier['lead_time_days']} days.",
        f"Budget permits up to {budget_limit} units and storage permits up to {storage_limit} additional units.",
    ]
    if need > 0 and (need < supplier["min_order_qty"] or safe_limit < supplier["min_order_qty"]):
        decision = {"decision": "investigate", "quantity": None,
                    "reasoning": "The real need or the safe purchase limit is below the supplier minimum order quantity, so a buyer must weigh the excess-stock trade-off.",
                    "key_factors": factors}
    elif existing_supply >= forecast * 0.9:
        decision = {"decision": "reject", "quantity": None,
                    "reasoning": "Existing inventory and open orders already cover forecast demand, so another purchase risks overstock.",
                    "key_factors": factors}
    elif recommended <= safe_limit and (existing_supply + recommended) / forecast <= 2.5:
        decision = {"decision": "accept", "quantity": recommended,
                    "reasoning": "The recommended quantity meets the demand gap and stays within the supplier, budget, storage, and overstock limits.",
                    "key_factors": factors}
    else:
        quantity = min(safe_limit, max(supplier["min_order_qty"], need))
        decision = {"decision": "modify", "quantity": quantity,
                    "reasoning": "The original recommendation is not safe under the current constraints, so the order is reduced to the largest sensible quantity that remains valid.",
                    "key_factors": factors}

    trace.append({"type": "decision", "input": decision})
    validation = validate_business_decision(recommendation, decision["decision"], decision["quantity"])
    return _complete_run(recommendation, trace, [decision], decision, validation, not validation["passed"])


def run_agent(recommendation: dict) -> dict:
    if AGENT_MODE == "demo":
        return _run_demo_agent(recommendation)
    if AGENT_MODE != "anthropic":
        raise RuntimeError("AGENT_MODE must be either 'demo' or 'anthropic'.")
    if not ANTHROPIC_API_KEY:
        raise RuntimeError("ANTHROPIC_API_KEY is not configured. Add it to backend/.env before running Anthropic mode.")

    client = Anthropic(api_key=ANTHROPIC_API_KEY)

    trace = []
    decision_history = []
    messages = [{
        "role": "user",
        "content": (
            "Review this purchase recommendation and decide what should happen:\n"
            f"{json.dumps(recommendation, indent=2)}"
        ),
    }]

    final_decision = None
    validation = None
    escalated = False

    for attempt in range(MAX_AGENT_REVISIONS + 1):
        decision = _investigate_and_decide(client, messages, trace)
        decision_history.append(decision)

        validation = validate_business_decision(
            recommendation, decision["decision"], decision.get("quantity")
        )

        if validation["passed"]:
            final_decision = decision
            break

        if attempt == MAX_AGENT_REVISIONS:
            # Out of revision attempts - do not auto-execute a decision that
            # fails business validation. Escalate instead.
            final_decision = decision
            escalated = True
            break

        # Feed the failure back to the model and let it revise. This lands in the
        # same user turn as the submit_decision tool_result above (merged by
        # _append_user), since no assistant turn happened in between.
        _append_user(messages, [{
            "type": "text",
            "text": (
                "Your proposed decision failed validation against the live data:\n"
                f"{json.dumps(validation['violations'], indent=2)}\n\n"
                "Re-check the relevant tools if needed, then call submit_decision again "
                "with a corrected decision."
            ),
        }])

    return _complete_run(recommendation, trace, decision_history, final_decision, validation, escalated)
